// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ServiceDeskLite.Infrastructure.Persistence;

#nullable disable

namespace ServiceDeskLite.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ServiceDeskLiteDbContext))]
    [Migration("20260305125517_AddTicketComments")]
    partial class AddTicketComments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("ServiceDeskLite.Domain.Tickets.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Assignee")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<long?>("DueAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Status");

                    b.ToTable("Tickets", (string)null);
                });

            modelBuilder.Entity("ServiceDeskLite.Domain.Tickets.Ticket", b =>
                {
                    b.OwnsMany("ServiceDeskLite.Domain.Tickets.Comment", "Comments", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Author")
                                .HasMaxLength(100)
                                .HasColumnType("TEXT");

                            b1.Property<string>("Content")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("TEXT");

                            b1.Property<long>("CreatedAt")
                                .HasColumnType("INTEGER");

                            b1.Property<Guid>("TicketId")
                                .HasColumnType("TEXT");

                            b1.HasKey("Id");

                            b1.HasIndex("CreatedAt");

                            b1.HasIndex("TicketId");

                            b1.ToTable("TicketComments", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("TicketId");
                        });

                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
